[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
  |\.hg
  |\.mypy_cache
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
)/
'''